name: dstft_env
channels:
  - pytorch  
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pytorch=2
  - ipykernel
  - ipympl
  - widgetsnbextension
  - ipywidgets
  - librosa
  - matplotlib
  - numpy
  - scipy
  - pandas
  - torchaudio
  - seaborn
  - streamlit
  - pytest
  - pip
  - pip:
    - -e .
