name: dstft_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2
  - ipykernel
  - ipympl
  - widgetsnbextension
  - ipywidgets
  - matplotlib
  - numpy
  - scipy
  - pandas
  - torchaudio
  - pip
  - pip:
    - -e .
